"""added tourist site

Revision ID: ed65df952db4
Revises: 8cda8dbc1bf1
Create Date: 2023-10-03 16:51:45.689328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed65df952db4'
down_revision = '8cda8dbc1bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('touristSite', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('touristSite')

    # ### end Alembic commands ###
